export const ClientCommand = {
  Ping: 0,
  Authenticate: 1,
  Chat: 2,
  Touches: 3,
  Judges: 4,
  CreateRoom: 5,
  JoinRoom: 6,
  LeaveRoom: 7,
  LockRoom: 8,
  CycleRoom: 9,
  SelectChart: 10,
  RequestStart: 11,
  Ready: 12,
  CancelReady: 13,
  Played: 14,
  Abort: 15,
} as const;

export const ServerCommand = {
  Pong: 0,
  Authenticate: 1,
  Chat: 2,
  Touches: 3,
  Judges: 4,
  Message: 5,
  ChangeState: 6,
  ChangeHost: 7,
  CreateRoom: 8,
  JoinRoom: 9,
  OnJoinRoom: 10,
  LeaveRoom: 11,
  LockRoom: 12,
  CycleRoom: 13,
  SelectChart: 14,
  RequestStart: 15,
  Ready: 16,
  CancelReady: 17,
  Played: 18,
  Abort: 19,
} as const;
